# Generated by Django 3.0.8 on 2020-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200806_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accpython',
            name='corr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accpython',
            name='opt1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accpython',
            name='opt2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accpython',
            name='opt3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accpython',
            name='opt4',
            field=models.CharField(max_length=100),
        ),
    ]
