# Generated by Django 3.0.8 on 2020-08-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200806_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accpython',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
    ]
